### ISSUE TITLE
/exchange is not working

### ISSUE THREAD

**Issue by lightphoenix2** [Zamirathe/ZaupShop#4]
the command /exchange is not working for the Uconomy Essential plugin

**Comment by Zamirathe** [comment]
Please try the latest download.  I just forgot to change the version number.  All commands are working for me.

**Comment by lightphoenix2** [comment]
Well, I have downloaded the latest version. And it is still not loading. In the console, the command was not loaded. I believe others are facing the same problem as stated in the comments of the plugin
